In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.3.0


In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [12]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
ann = tf.keras.models.Sequential()

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4828 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4525 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4341 - accuracy: 0.7971
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.7997
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8021: 0s - loss: 0 - ETA: 0s - loss: 0.4245 - accuracy: 0.
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4164 - accuracy: 0.8045
Epoch 8/100
250/250 [==============================] - ETA: 0s - loss: 0.4072 - accuracy: 0.80 - 1s 3ms/step - loss: 0.4086 - accuracy: 0.8066
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3988 - accuracy: 0.

250/250 [==============================] - 0s 871us/step - loss: 0.3345 - accuracy: 0.8660
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8665
Epoch 79/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3347 - accuracy: 0.8655
Epoch 80/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3342 - accuracy: 0.8655
Epoch 81/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3342 - accuracy: 0.8659
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3342 - accuracy: 0.8656
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8650
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3338 - accuracy: 0.8644
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8656
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1503   92]
 [ 188  217]]


In [23]:
acc = accuracy_score(y_test, y_pred)
acc

0.86